import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { demoProducts } from './catalog';

const note = 'DEMO ONLY · Changes are not saved and this screen is not connected to a live server.';
const orders = [
  { id: 'VH-1042', date: 'May 18, 2025', status: 'Delivered', total: '$213.99', item: 'Studio Microphone' },
  { id: 'VH-1038', date: 'May 16, 2025', status: 'Processing', total: '$84.99', item: 'Monitor Headphones' },
  { id: 'VH-1029', date: 'May 12, 2025', status: 'Shipped', total: '$159.50', item: 'USB Audio Interface' },
];
function DemoNote() { return <p className="demo-note" role="note">{note}</p>; }
export function Account() {
  const [params, setParams] = useSearchParams();
  const [saved, setSaved] = useState(false);
  const section = params.get('section') ?? 'orders';
  const order = orders.find(item => item.id === params.get('order'));
  return <div className="public-shell"><header className="public-header"><Link className="brand" to="/account">VoiceHub<span className="brand-pay">Pay</span></Link><nav aria-label="Account navigation"><Link to="/shop">Shop</Link><Link to="/account" aria-current="page">My account</Link><Link to="/admin">Admin</Link></nav></header><main className="public-content"><p className="eyebrow">ACCOUNT · PREVIEW</p><h1>My account</h1><DemoNote/><nav className="tabs" aria-label="Account sections">{['orders','profile','security'].map(key=><button key={key} type="button" aria-pressed={section===key} onClick={()=>setParams({section:key})}>{key[0].toUpperCase()+key.slice(1)}</button>)}</nav>
{order ? <section className="card"><Link to="/account">← Back to orders</Link><h2>Order {order.id}</h2><p>{order.date} · <strong>{order.status}</strong></p><table aria-label="Order items"><thead><tr><th scope="col">Item</th><th scope="col">Quantity</th><th scope="col">Total</th></tr></thead><tbody><tr><td>{order.item}</td><td>1</td><td>{order.total}</td></tr></tbody></table><p>Order total: <strong>{order.total}</strong></p><DemoNote/></section> : section === 'profile' ? <form className="card demo-form" onSubmit={event=>{event.preventDefault();setSaved(true)}}><h2>Profile details</h2><label htmlFor="display-name">Display name</label><input id="display-name" defaultValue="Alex Morgan"/><label htmlFor="account-email">Email address</label><input id="account-email" type="email" defaultValue="alex@example.com"/><button className="button button-primary" type="submit">Save profile (demo)</button>{saved&&<p role="status">Demo profile updated locally. Nothing was saved to a server.</p>}</form> : section === 'security' ? <section className="card"><h2>Security</h2><p>Password changes are disabled in this demo.</p><button className="button button-outline" disabled>Change password unavailable</button><p>Two-factor authentication is not connected.</p></section> : <section className="card"><h2>Order history</h2><table aria-label="Demo orders"><thead><tr><th scope="col">Order</th><th scope="col">Date</th><th scope="col">Status</th><th scope="col">Total</th></tr></thead><tbody>{orders.map(item=><tr key={item.id}><td><Link to={`/account?order=${item.id}`}>Order #{item.id}</Link></td><td>{item.date}</td><td>{item.status}</td><td>{item.total}</td></tr>)}</tbody></table></section>}</main></div>;
}
export function Admin() {
 const [view,setView]=useState<'products'|'orders'>('products'); const [form,setForm]=useState(false); const [saved,setSaved]=useState(false);
 return <div className="public-shell"><header className="public-header"><Link className="brand" to="/admin">VoiceHub<span className="brand-pay">Pay</span></Link><nav aria-label="Admin navigation"><Link to="/shop">Shop</Link><Link to="/account">My account</Link><Link to="/admin" aria-current="page">Admin</Link></nav></header><main className="public-content"><p className="eyebrow">ADMINISTRATION · PREVIEW</p><h1>Admin console</h1><p>Product management and inventory</p><DemoNote/><nav className="tabs" aria-label="Admin sections"><button aria-pressed={view==='products'} onClick={()=>setView('products')}>Products</button><button aria-pressed={view==='orders'} onClick={()=>setView('orders')}>Orders</button></nav>{view==='products'?<><div className="section-heading"><h2>Product inventory</h2><button className="button button-primary" onClick={()=>setForm(!form)}>Add product</button></div>{form&&<form className="card demo-form" onSubmit={event=>{event.preventDefault();setSaved(true)}}><h2>Add product · demo</h2><label htmlFor="product-name">Product name</label><input id="product-name" required/><label htmlFor="product-price">Price (USD)</label><input id="product-price" type="number" min="0" step="0.01" required/><label htmlFor="product-stock">Inventory quantity</label><input id="product-stock" type="number" min="0" required/><button className="button button-primary">Save demo product</button>{saved&&<p role="status">Demo product staged locally; no server changes made.</p>}</form>}<table aria-label="Product inventory"><thead><tr><th scope="col">Product</th><th scope="col">Category</th><th scope="col">Price</th><th scope="col">Inventory</th><th scope="col">Status</th></tr></thead><tbody>{demoProducts.map((product,index)=><tr key={product.id}><td>{product.name}</td><td>{product.category}</td><td>${(product.priceCents/100).toFixed(2)}</td><td>{[12,0,7][index]}</td><td>{index===1?'Out of stock':'In stock'}</td></tr>)}</tbody></table></>:<section className="card"><h2>Recent orders</h2><table aria-label="Admin orders"><thead><tr><th scope="col">Order</th><th scope="col">Status</th><th scope="col">Total</th></tr></thead><tbody>{orders.map(item=><tr key={item.id}><td>{item.id}</td><td>{item.status}</td><td>{item.total}</td></tr>)}</tbody></table></section>}</main></div>;
}
